import pandas as pd
import numpy as np
import sys
import re
import datetime as dt
from datetime import timedelta
from matplotlib import pyplot as plt
from ATSIDriver import *  


#exec(open('/Users/cartercribbs/VCV/EnergyData/ATSIDriver.py').read())


'''
Here we construct the csv file name that will be generated by the driver file
'''
yesterday_date = dt.date.today() - timedelta(2)
ten_days_ago = dt.date.today() - timedelta(11)
str_yesterday = yesterday_date.strftime("%Y%m%d")
str_tenago = ten_days_ago.strftime("%Y%m%d")
csv_file_name = str_tenago + "-" + str_yesterday + " PJM Day-Ahead Price For Hubs.csv"

'''
Here we read the CSV of hourly locational marginal pricing (LMP) from different energy HUBS in PJM's power grid
'''

lmp = pd.read_csv("/Users/cartercribbs/Downloads/" + csv_file_name)
#print(lmp['node_name'].unique())
lmp = lmp.loc[lmp['node_name']=='ATSI GEN HUB']
lmp.index = np.arange(0, len(lmp))
#print(lmp)
#print(one_week_ago)
for k in range(len(lmp)):
    old_date = lmp.iloc[k]['Date']
    new_date = re.split('\s', old_date)[0]
    #print(type(new_date))
    
    if(new_date[1]=="/"):
        new_date = "0" + new_date
    if(new_date[4]=="/"):
        new_date = new_date[0:3] + "0" + new_date[3:]  
    #print(new_date)
    format_str = "%m/%d/%Y"
    date_time = dt.datetime.strptime(new_date, format_str)
    lmp.iloc[k,0]= date_time
    
    

'''
#Here we are working with LMP data soley from ATSI power hub  
'''

lmp_dayMean = lmp.groupby('Date').agg('mean')
lmp_dayMean = lmp_dayMean.reset_index()
lmp_dayMean['Date'] = pd.to_datetime(lmp_dayMean['Date'])
lmp_dayMean = lmp_dayMean.sort_values(by='Date')
lmp_dayMean = lmp_dayMean.reset_index()
lmp_dayMean = lmp_dayMean.drop('index', axis=1)
#lmp_dayMean = lmp_dayMean[-4:-1]
#print(lmp_dayMean)


'''
Generate Line Graph for Ten-Day LMP
'''
plt.style.use('seaborn')
lmp_chart = lmp_dayMean.plot('Date', 'total_lmp', color = "k", linestyle = '--', linewidth = 3, marker = 'D', markerfacecolor = 'yellow', markeredgecolor = 'yellow')
ax = plt.gca()
for axis in ['top', 'bottom', 'left', 'right']:
    ax.spines[axis].set_linewidth(2.5) #change width
    ax.spines[axis].set_color('#8B8989') #change color
plt.xlabel ('Date')
plt.ylabel('Day-Ahead LMP (Dollars/MWH)')
plt.legend(prop={'size':20})
plt.tight_layout()
plt.title("Ten Day Daily Average LMP Rate of ATSI Gen Hub from PJM")

plt.show()
